export const GET_TASKS = 'GET_TASKS';

export const SET_CREDENTIALS = 'SET_CREDENTIALS';
export const DELETE_CREDENTIALS = 'DELETE_CREDENTIALS';
export const SET_TASK_TO_SHOW = 'SET_TASK_TO_SHOW';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const SET_TASK_PER_PAGE = 'SET_TASK_PER_PAGE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
